
INSERT SEXes(NAME) VALUES('MALE')
INSERT SEXes(NAME) VALUES('FEMALE')

INSERT breeds(NAME) VALUES('Cleveland Bay')
INSERT breeds(NAME) VALUES('Angloarab')
INSERT breeds(NAME) VALUES('Furioso')
INSERT breeds(NAME) VALUES('Haflinger')
INSERT breeds(NAME) VALUES('Irish Draught')
INSERT breeds(NAME) VALUES('koń woroneski')
INSERT breeds(NAME) VALUES('kłusak rosyjski')
INSERT breeds(NAME) VALUES('koń nowokirgiski')
INSERT breeds(NAME) VALUES('Quarter Horse')
INSERT breeds(NAME) VALUES('Zweibrucker')

INSERT bodyTypes(NAME) VALUES('HATCHBACK')
INSERT bodyTypes(NAME) VALUES('SEDAN')
INSERT bodyTypes(NAME) VALUES('COUPE')
INSERT bodyTypes(NAME) VALUES('KOMBI')
INSERT bodyTypes(NAME) VALUES('CABRIOLET')

INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(3,1.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(3,1.2)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(3,1.4)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(3,1.6)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(4,1.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(4,1.2)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(4,1.4)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(4,1.6)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(4,1.8)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(6,3.2)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(6,3.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(6,4.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(6,2.5)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(6,2.8)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,4.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,4.2)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,4.8)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,5.0)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,5.2)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,6.8)
INSERT engineTypes(CYLINDERAMOUNT,EngineCapacity) VALUES(8,7.0)

INSERT brands(NAME) VALUES('MERCEDES')
INSERT brands(NAME) VALUES('VOLKSWAGEN')
INSERT brands(NAME) VALUES('FIAT')
INSERT brands(NAME) VALUES('BMW')
INSERT brands(NAME) VALUES('AUDI')
INSERT brands(NAME) VALUES('TOYOTA')
INSERT brands(NAME) VALUES('CITROEN')

INSERT colors(NAME) VALUES('CZERWONY')
INSERT colors(NAME) VALUES('NIEBIESKI')
INSERT colors(NAME) VALUES('SREBRNY')
INSERT colors(NAME) VALUES('CZARNY')
INSERT colors(NAME) VALUES('GRANATOWY')


INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Bardzo dobry koń, bardzo',2000,'Jacek','Horse',1,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Jak gepard panie',3000,'Placek','Horse',2,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Mocne nogi ma',10000,'Plankton','Horse',3,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Bardzo dobry koń, bardzo',2000,'Sebek','Horse',4,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Jak gepard panie',33000,'Wurst','Horse',5,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Mocne nogi ma',9000,'Wezuwiusz','Horse',6,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Mocny jak wół',1050,'Kopacek','Horse',1,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Jak dobry dość tak',3100,'Klacek','Horse',2,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Mocne nogi ma',10400,'Roman','Horse',7,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Nie zawiedzie was',2000,'Ogar','Horse',4,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Jak gepard panie albo dwa',23000,'Komar','Horse',5,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Z bólem serca, ale musimy go sprzedać',7000,'Eryk','Horse',6,1)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Mocne nogi ma',10000,'Romana','Horse',7,2)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Nie zawiedzie was',8000,'Ogara','Horse',4,2)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Jak gepard panie albo dwa',21000,'Komara','Horse',5,2)
INSERT Products(Description,Price,Name,Discriminator,Breed_Id,Sex_Id) Values('Z bólem serca, ale musimy ją sprzedać',4000,'Eryk','Horse',6,2)


INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Daje rade fura',9000,'Golf III','Car',1,1,1,2)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Dobra fura',2000,'Golf II','Car',2,1,2,2)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Wiadomo co to za auto. Klasa.',111000,'S class','Car',1,1,9,1)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Auto kosmicznej klasy',234000,'Z class','Car',2,1,8,1)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Auto dla biedaków',9000,'Seicento','Car',1,2,1,3)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Dobra fura dla biedaków',2000,'Seicento 76','Car',2,2,2,3)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Gwarancja dobrych łowów na każdej imprezie',51000,'e46','Car',4,3,16,4)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Prawdziwa gwarancja dobrych łowów na każdej imprezie',2341000,'e666','Car',3,5,11,4)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Najprawdziwsza gwarancja dobrych łowów na każdej imprezie',2114000,'e121212','Car',3,5,12,4)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Sam mam(Admin), polecam.',60000,'A4','Car',1,1,19,5)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Dobra fura',15000,'A4','Car',2,1,14,5)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Sam mam(Mod), polecam.',60000,'Yaris','Car',1,1,19,6)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Samochód Karola',54000,'Karolla','Car',2,1,14,6)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Niezawodny.',111000,'C5','Car',5,2,9,7)
INSERT Products(Description,Price,Name,Discriminator,BodyType_Id,Color_Id,EngineType_Id,Brand_Id) Values('Git auto',234000,'C4','Car',5,2,8,7)